# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
import numpy as np

print(np.zeros((2,3)))
print(np.empty((2,3)))


[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


* empty
    * Return a new array of given shape and type, *without initializing entries*.


* zeros
    * Return a new array of given shape and type, filled with zeros.

---
* References
  * https://numpy.org/doc/stable/reference/generated/numpy.empty.html

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [8]:
# 參考解答
import numpy as np

a = np.random.rand(2, 3)
a = a * 100
print(a)
print(a.round())
print(a.round().dtype)

[[13.25887407 77.24418787 22.22475605]
 [63.50330824 15.17601338 54.86408268]]
[[13. 77. 22.]
 [64. 15. 55.]]
float64


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [18]:
m = 20
n = 40
sizeX = 2
sizeY = 3

a = np.random.rand(sizeX, sizeY) * (n-m)
a += m
print(a.round())

[[32. 35. 20.]
 [31. 25. 39.]]


'\nYour Code\n'