# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [13]:
import numpy as np


a = np.array( [20, 30, 40, 50] )

b = np.array( [1, 2, 3, 4])

c = 1

d = np.array( [1])

e = np.array( [1, 2] )

print(a + a)
print(a + b)
print(a + c)
print(a + d)
# print(a + e)  錯誤  不知道 e 要如何與  a 進行 廣播 加法

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [31]:
import numpy as np

A = np.ones(3)*1
B = np.ones(3)*2

print(A)
print(B)

print((A+B)*(-A/2))

c = np.array([ (A[x]+B[x])*(-A[x]/2) for x in range(len(A))]) 
print(c)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [42]:
A = np.ones((1,6))
B = np.ones((6,1))
print(A)
print(B)
print('\n')

print (A * B)   ## alternative print(np.dot(A,B))
print (A @ B)   

[[1. 1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
