# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [19]:
'''
Your Code
'''

a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [20]:
import numpy as np 

aNp = np.arange(10)
aNp

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(sum(a))
print(sum(aNp))

10
45


### 解答
1. lists, tuples, and np 中 array 皆可以用 內建函數 `sum()` 使用, `a.sum() `與 `np.sum()` 所適用的是 np 函式庫中的函數, 其中 `a.sum()`使用的是 a 物件裡面的方法。

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [50]:
A = np.random.random((5, 5))
print(A)
row_sums = A.sum(axis=1)
A = A / row_sums[:, np.newaxis]
print(A)

[[0.64166798 0.19244395 0.7620631  0.95865891 0.52128796]
 [0.37057489 0.71741519 0.63056931 0.9490718  0.57477458]
 [0.0900378  0.36406966 0.66358284 0.14213058 0.42621113]
 [0.69453743 0.63803566 0.89158297 0.51864158 0.06245852]
 [0.10550669 0.94358566 0.75917902 0.56787203 0.53181224]]
[[0.20859641 0.06256057 0.24773501 0.31164529 0.16946271]
 [0.1142901  0.22126015 0.19447576 0.29270605 0.17726794]
 [0.05340219 0.21593283 0.39357666 0.08429886 0.25278946]
 [0.24758432 0.22744292 0.31782587 0.18488207 0.02226482]
 [0.03628208 0.3244842  0.26106967 0.19528222 0.18288183]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [38]:
A = np.random.random((5))
print(A)
A = A / np.linalg.norm(A) * 10
A[np.argmax(A)] = -1
print(A)

[0.44450946 0.68516664 0.75087691 0.6369879  0.9651992 ]
[ 2.77373389  4.27543192  4.68546328  3.97479715 -1.        ]
