# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
import numpy as np

In [2]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
Z1 = Z
Z2 = Z
Z3 = Z
Z4 = Z

#### 測試是否成功對每一個元增加

In [3]:

t = np.arange(6)
for i in range(len(t)):
    t[i] += 1

In [4]:
t = np.arange(8).reshape(2, 2, 2)
t = np.add(t, 1)
for i in range(len(t)):
    for j in range(len(t[i])):
        for k in range(len(t[i][j])):
            t[i][j][k] += 1
            
with np.nditer(t, op_flags=['readwrite']) as it:
    for x in it:
        x[...] += 1 

for it in t:
    it[...] +=1

t

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

#### 測試效率

In [5]:
%timeit -n 10 a = 2

for i in range(len(Z)):
    for j in range(len(Z[i])):
        for k in range(len(Z[i][j])):
            Z[i][j][k] += 1

14.3 ns ± 3.05 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
%timeit -n 10 a = 2

Z1 = np.add(Z1, 1)

17.3 ns ± 8.46 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%timeit -n 10 a = 2
            
with np.nditer(Z2, op_flags=['readwrite']) as it:
    for x in it:
        x[...] += 1

19.1 ns ± 8.58 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%timeit -n 10 a = 2

for it in Z3:
    it[...] +=1

15.5 ns ± 4.83 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [9]:

Z = np.random.randint(0,10,50)
print(Z)


[7 9 7 0 6 4 2 9 3 4 4 4 3 8 5 0 6 4 6 7 2 8 1 9 9 3 1 3 3 3 6 9 8 0 2 6 1
 7 8 6 2 6 2 5 2 3 3 0 0 6]


In [10]:
val_idx = dict()
val_cnt = dict()
# val_cnt[Z[0]] = np.array([0])
for i in range(len(Z)):
    if Z[i] in val_idx:
        val_idx[Z[i]] = np.append(val_idx[Z[i]], i)
        val_cnt[Z[i]] += 1
    else:
        val_idx[Z[i]] = np.array([i])
        val_cnt[Z[i]]  = 1
    # val_cnt[Z[i]]


max_key = max(val_cnt, key = val_cnt.get)
print(f"最多重複的數字為：{max_key}")
print(f"分別出現在：{val_idx[max_key]}")

最多重複的數字為：6
分別出現在：[ 4 16 18 30 35 39 41 49]


In [25]:
count = np.bincount(Z)    # array([7, 4, 0, 4, 5, 5, 6, 6, 6, 7])
max_count = np.max(count)  # 7

ans = np.argwhere(count == max_count)  # 找出所有頻率為 max 的位置 (此範例是找頻率為 7 的) 
ans = ans.flatten().tolist()     # 轉成一維的 list，輸出為 [0, 9]

print(ans)

[3, 6]


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [11]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[1, 2, 3, 6, 1, 6]
[1, 2, 3, 6, 1, 6]


In [12]:
# 答案
def my_tolist2(b):
    print("[", end="")
    for i in range(len(b)):
        if (i < len(b)-1):
            print(list(b[i]), end =", ")
        else:
            print(list(b[i]), end = "]")

In [13]:
b = np.random.randint(10, size=(3,4)) 
print(b.tolist())
my_tolist2(b)

[[2, 5, 9, 9], [9, 5, 1, 0], [2, 8, 4, 2]]
[[2, 5, 9, 9], [9, 5, 1, 0], [2, 8, 4, 2]]

In [14]:
def my_tolist3(b):
    print("[", end="")
    for i in range(len(b)):
        if (i < len(b)-1):
            my_tolist2(b[i])
            print(", ", end="")
        else:
            my_tolist2(b[i])
    print("]")

In [15]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
# print(list(c))
my_tolist3(c)

[[[9, 5], [0, 8], [0, 9]], [[1, 6], [2, 3], [4, 3]]]
[[[9, 5], [0, 8], [0, 9]], [[1, 6], [2, 3], [4, 3]]]


> 注意：此題應該可以使用遞迴方完整判斷出幾層 array

In [16]:
def my_tolist(iterable):
    if type(iterable) != np.array:
        return iterable
    return [my_tolist(obj) for obj in iterable]

In [20]:
print(list(my_tolist(a)))

[1, 2, 3, 6, 1, 6]


In [23]:
print(my_tolist(b))

[[2 5 9 9]
 [9 5 1 0]
 [2 8 4 2]]


In [19]:
print(my_tolist(c))

[[[9 5]
  [0 8]
  [0 9]]

 [[1 6]
  [2 3]
  [4 3]]]
