# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np

a = np.arange(15).reshape(3, 5)  # #row and #column, represent 3 and 5, re.,..
print('list(a):', list(a))       # 只有第一層的被展開 (rows) 
print('tolist(a):', a.tolist())  # 使用np 中的 物件展開
# 答案顯現方式不同

list(a): [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist(a): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [2]:
# 記得先 Import 正確的套件

a = np.random.randint(10, size=6)


print(a) 
print(a.ndim) 
print(a.shape)
print(a.size)
print(a.dtype) 
print(a.itemsize) 
print(len(a)) 
print(type(a))

[3 3 4 4 7 4]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [3]:
b = np.random.randint(10, size=(3,4)) 

print(b)          
print(b.ndim)     # ndim
print(b.shape)    # the dimentional size
print(b.size)     # the size of data
print(b.dtype)    # data_type  int64
print(b.itemsize) # item size, int64花8位元
print(len(b))      #第一層陣列
print(type(b))    #物件類型

[[8 5 4 0]
 [7 7 6 0]
 [3 7 9 6]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [4]:
c = np.random.randint(10, size=(2,3,2)) 

print(c) 
print(c.ndim) 
print(c.shape) 
print(c.size) 
print(c.dtype) 
print(c.itemsize) 
print(len(c))  
print(type(c)) 

[[[9 3]
  [8 0]
  [5 5]]

 [[7 0]
  [9 8]
  [4 2]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [5]:
a = np.random.randint(10, size=6) 
print(a.tolist())
print(list(a))

[1, 5, 5, 7, 2, 2]
[1, 5, 5, 7, 2, 2]


In [6]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())

print([ list(b[x]) for x in range(len(b)) ])

[[8, 1, 7, 5], [2, 3, 3, 3], [8, 4, 7, 8]]
[[8, 1, 7, 5], [2, 3, 3, 3], [8, 4, 7, 8]]


In [7]:
c = np.random.randint(10, size=(3,3,3)) 

print(c.tolist())

print([[ list(c[x][y]) for x in range(len(c[y]))] for y in range(len(c)) ])

[[[3, 3, 4], [0, 3, 4], [2, 5, 4]], [[5, 4, 1], [3, 9, 4], [0, 6, 8]], [[0, 5, 7], [5, 4, 0], [5, 9, 0]]]
[[[3, 3, 4], [5, 4, 1], [0, 5, 7]], [[0, 3, 4], [3, 9, 4], [5, 4, 0]], [[2, 5, 4], [0, 6, 8], [5, 9, 0]]]


In [8]:
def tolist(inA):
    # the boundaies of one dimential array for recursive
    if type(inA) != np.ndarray:
        return inA

    newVec = []

    for x in inA:
        newVec.append(tolist(x))

    return list(newVec)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[1, 5, 5, 7, 2, 2]
[[8, 1, 7, 5], [2, 3, 3, 3], [8, 4, 7, 8]]
[[[3, 3, 4], [0, 3, 4], [2, 5, 4]], [[5, 4, 1], [3, 9, 4], [0, 6, 8]], [[0, 5, 7], [5, 4, 0], [5, 9, 0]]]


In [9]:
# Alternative
def tolist(inA):
    # the boundaies of one dimential array for recursive
    if type (inA) != np.ndarray:
        return inA
    return [tolist(x) for x in inA]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[1, 5, 5, 7, 2, 2]
[[8, 1, 7, 5], [2, 3, 3, 3], [8, 4, 7, 8]]
[[[3, 3, 4], [0, 3, 4], [2, 5, 4]], [[5, 4, 1], [3, 9, 4], [0, 6, 8]], [[0, 5, 7], [5, 4, 0], [5, 9, 0]]]
